app:
  name: "web_app"
  mode: "dev"
  port: 8081
  version: "v0.1.1"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: 8.130.40.129
  port: 3306
  user: "root"
  password: "S21070078"
  dbname: "itcast"
  max_open_connections: 200
  max_idle_connections: 10
redis:
  host: "8.130.40.129"
  port: 6379
  password: "S21070078"
  db: 0
  pool_size: 100